# 이 워크플로우는 update.py 파일을 실행합니다. 즉 README.md 파일을 업데이트합니다.

name: Update readme # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [ "main" ] # main 브랜치에 push가 발생했을 때
  pull_request:

jobs: # 실제 실행될 내용
  build:
    runs-on: ubuntu-latest # 빌드 환경
    steps:
    - name: Checkout repository # 저장소 체크아웃
      uses: actions/checkout@v3 # checkout
    - name: Set up Python 3.11 
      uses: actions/setup-python@v3 # setup-python
      with:
        python-version: "3.11" # 최신 버전 파이썬 사용
    - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update.py # 2) update.py 실행
      run: |
        python update.py
    - name: Configure Git # Git 설정
      run: |
        git config --global user.name 'totoroto' # 수정된 사용자명
        git config --global user.email 'lsb0496@naver.com' # 수정된 이메일
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git add -A
        git commit -am "auto update README.md" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git push
